### ISSUE TITLE
希望能有只显示中大破的选项

### ISSUE THREAD

**Issue by wafer-li** [Javran/poi-plugin-docking#1]
为了计划渠位使用，需要隐藏能被明石修理的船。

只显示出中大破船用来入渠修理

**Comment by Javran** [comment]
好,可以加

**Comment by Javran** [comment]
0.4.0 发布, 新加个过滤器, 多次点击可在 "损害: 全部 / ≤小破 / >小破" 三个状态间切换

![2018-01-03_231718_3840x1080_scrot](https://user-images.githubusercontent.com/1096354/34550130-54d10096-f0dc-11e7-8f62-00f4c79b5217.jpg)
