### ISSUE TITLE
不能及时更新舰娘血量

### ISSUE THREAD

**Issue by wafer-li** [Javran/poi-plugin-docking#3]
对于刚修好的舰娘，点入入渠界面后不能及时更新其血量，必须回一次母港才能刷新

图没截好，等下补

**Comment by wafer-li** [comment]
![](https://ws3.sinaimg.cn/large/006tKfTcly1fn4jfi1hwvj30hg0h3q54.jpg)
![](https://ws1.sinaimg.cn/large/006tKfTcly1fn4jnue3xcj30gr0gx76a.jpg)
![image](https://user-images.githubusercontent.com/12459199/34551944-9bc5d870-f161-11e7-8a58-64437103a774.png)

**Comment by Javran** [comment]
@wafer-li 老问题了,田中的API只告诉你澡堂里有哪些船,而哪些已经修理完成了只能自行判断,我感觉这个想完美解决要改本体,让我想想.

**Comment by Javran** [comment]
等poi本体更新下一个版本就会解决,届时有问题再开.

**Comment by wafer-li** [comment]
@Javran 
我都是直接 Pull 最新 commit 的，不存在下个版本的问题

**Comment by Javran** [comment]
@wafer-li 了解,那现在的版本应该正常了.
